#!/bin/bash

# 🎯 WISE TRADE - HOW TO RUN THE APP
# ===================================

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║          🚀 Wise Trade - Quick Start Commands 📈            ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "📌 You have Node $(node --version)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  OPTION 1: Run with helper script (RECOMMENDED)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Terminal 1 - Backend:"
echo "  $ cd /home/johanan/wise-Trade"
echo "  $ source myenv/bin/activate"
echo "  $ uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
echo ""
echo "  Terminal 2 - Frontend:"
echo "  $ cd /home/johanan/wise-Trade"
echo "  $ ./start-frontend.sh"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  OPTION 2: Run with command bypass (if script fails)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  $ cd /home/johanan/wise-Trade/frontend"
echo "  $ unset -f npm && unset -f npx && command npm run dev"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  OPTION 3: Fix proxy permanently (one-time fix)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Edit ~/.bashrc and find these lines:"
echo "    npm () { command http_proxy=\"\" https_proxy=\"\" npm \"\$@\" }"
echo "    npx () { command http_proxy=\"\" https_proxy=\"\" npx \"\$@\" }"
echo ""
echo "  Replace them with:"
echo "    npm () { env http_proxy=\"\" https_proxy=\"\" npm \"\$@\" }"
echo "    npx () { env http_proxy=\"\" https_proxy=\"\" npx \"\$@\" }"
echo ""
echo "  Then: source ~/.bashrc"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🌐 Access your app at: http://localhost:3000"
echo ""
echo "📚 Documentation:"
echo "   - QUICK_START.md    - Quick start guide"
echo "   - PROJECT_COMPLETE.md - Full project overview"
echo "   - SETUP_GUIDE.md    - Detailed setup"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

