import { useState, useCallback, useRef } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import axios from 'axios';
import { API_BASE_URL } from '../config/config';

const fetchMarketImpactNews = async (limit = 10, forceRefresh = false) => {
  const params = { limit };
  if (forceRefresh) params.force_refresh = true;
  const token = localStorage.getItem('token');
  const response = await axios.get(`${API_BASE_URL}/ai/market-impact`, {
    params,
    headers: token ? { Authorization: `Bearer ${token}` } : {},
  });
  return { ...response.data, fetched_at: new Date().toISOString() };
};

export function useMarketImpactNews(limit = 10, options = {}) {
  const queryClient = useQueryClient();

  const query = useQuery({
    queryKey: ['marketImpactNews', limit],
    queryFn: () => fetchMarketImpactNews(limit, false),
    staleTime: Infinity,
    refetchInterval: false,
    refetchOnWindowFocus: false,
    ...options,
  });

  const forceRefresh = useCallback(async () => {
    const data = await fetchMarketImpactNews(limit, true);
    queryClient.setQueryData(['marketImpactNews', limit], data);
    return data;
  }, [limit, queryClient]);

  return { ...query, forceRefresh };
}

/**
 * Streaming hook for deep dive analysis via SSE.
 * Streams text as it's generated by the backend.
 */
export function useNewsAnalysis() {
  const [streamingText, setStreamingText] = useState('');
  const [phase, setPhase] = useState(null); // 'collecting' | 'synthesizing' | 'cached' | 'done' | 'error'
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState(null);
  const [data, setData] = useState(null);
  const abortRef = useRef(null);

  const analyze = useCallback(async (query) => {
    // Abort any in-flight request
    if (abortRef.current) abortRef.current.abort();
    const controller = new AbortController();
    abortRef.current = controller;

    setIsLoading(true);
    setStreamingText('');
    setPhase('collecting');
    setError(null);
    setData(null);

    try {
      const token = localStorage.getItem('token');
      const response = await fetch(
        `${API_BASE_URL}/ai/analyze-news/stream?query=${encodeURIComponent(query)}`,
        {
          headers: { 'Authorization': `Bearer ${token}` },
          signal: controller.signal,
        }
      );

      if (!response.ok) {
        throw new Error(`Server error: ${response.status}`);
      }

      const reader = response.body.getReader();
      const decoder = new TextDecoder();
      let buffer = '';
      let accumulated = '';

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;

        buffer += decoder.decode(value, { stream: true });

        // Parse SSE events from buffer
        const parts = buffer.split('\n\n');
        buffer = parts.pop(); // keep incomplete event in buffer

        for (const part of parts) {
          if (!part.trim()) continue;

          const eventMatch = part.match(/event:\s*(.+)/);
          const dataMatch = part.match(/data:\s*(.+)/);
          if (!eventMatch || !dataMatch) continue;

          const eventType = eventMatch[1].trim();
          let eventData;
          try {
            eventData = JSON.parse(dataMatch[1].trim());
          } catch {
            continue;
          }

          switch (eventType) {
            case 'status':
              setPhase(eventData.phase);
              break;
            case 'delta':
              accumulated += eventData.text;
              setStreamingText(accumulated);
              break;
            case 'done':
              setData({ analysis: eventData.full_text, query });
              setPhase('done');
              break;
            case 'error':
              setError(eventData.message);
              setPhase('error');
              break;
          }
        }
      }
    } catch (err) {
      if (err.name !== 'AbortError') {
        setError(err.message);
        setPhase('error');
      }
    } finally {
      setIsLoading(false);
    }
  }, []);

  const reset = useCallback(() => {
    if (abortRef.current) abortRef.current.abort();
    setStreamingText('');
    setPhase(null);
    setIsLoading(false);
    setError(null);
    setData(null);
  }, []);

  return {
    analyze,
    streamingText,
    phase,
    data,
    isLoading,
    isError: phase === 'error',
    error,
    reset,
  };
}

export function useCachedNewsAnalysis(query) {
  return useQuery({
    queryKey: ['newsAnalysis', query],
    queryFn: async () => {
      const token = localStorage.getItem('token');
      const response = await axios.get(`${API_BASE_URL}/ai/analyze-news`, {
        params: { query },
        headers: token ? { Authorization: `Bearer ${token}` } : {},
      });
      return response.data;
    },
    enabled: false,
    staleTime: 600000,
  });
}
